Iteratee is lost when _merge_with is recursing (#163).
dgilland/pydash pull request #164
Opened 2021-06-26 09:07 UTC by weineel

fix #163

2021-06-26 17:29 UTC, slallum approved these changes

2021-06-26 23:17 UTC, dgilland requested changes

2021-06-26 23:17 UTC, dgilland commented on tests/test_objects.py
>                  lambda a, b: a + b if isinstance(a, list) else b,
This test fails with this iteratee but can be made to pass by changing `else b` to `else None`. When `None` is returned by a custom iteratee, the `None` is ignored and the merge will recurse if conditions are met. But when a non-`None` value is returned, the recursion won't happen. I was able to get the tests passing locally with `lambda a, b: a + b if isinstance(a, list) else None`.

2021-06-26 23:17 UTC, dgilland commented on tests/test_objects.py
> +                {"fruits": ["apple"], "ohters": { "vegetables": ["beet"]}},
Running `inv black` from the project root or `black tests/test_objects.py` will fix the formatting and make flake8 happy.

2021-06-27 18:14 UTC, dgilland approved these changes

2021-06-27 18:14 UTC, merged

2021-06-27 18:19 UTC, dgilland commented
Thanks for fixing this! 👍